### ISSUE TITLE
Rename/Move package: io.scif.common

### ISSUE THREAD

**Issue by dietzc** [scifio/scifio-bf-compat#10]
Hi @hinerm,

could you rename the package https://github.com/scifio/scifio-bf-compat/tree/master/src/main/java/io/scif/common? Same problem as with imglib2.meta in imagej.commons: OSGi does not allow packages with the same name in different bundles. There is already a package with the same name in: io.scif (https://github.com/scifio/scifio/tree/master/src/main/java/io/scif/common). If its not possible to resolve this conflict, there are ways (hacks ;-)) to do that on OSGi side. However, it would be great if we could resolve it here.

Thanks!

Christian

**Comment by ctrueden** [comment]
I agree that all classes in `scifio-bf-compat` should have a common base package name. The `io.scif.common.RandomAccessInputStreamWrapper` class should be moved.

**Comment by hinerm** [comment]
Sounds good.. how about `io.scif.bf.wrapper` ?

Also, since OSGi doesn't allow packages with the same name, how can the deprecated classes still exist in [imagej-common](https://github.com/imagej/imagej-common/tree/7a7e541099b58f8e1918fa6e9a16cf69729610d1/src/test/java/net/imglib2/meta)?

Just want to make sure it's OK for me to deprecate `RandomAccessInputStreamWrapper` as well.

Thanks @dietzc !

**Comment by hinerm** [comment]
https://github.com/scifio/scifio-bf-compat/commit/027d38f455701ec2a7647844ad64a83481b5f68c look good?

**Comment by ctrueden** [comment]
:+1:

**Comment by dietzc** [comment]
:+1:

**Comment by hinerm** [comment]
Released in https://github.com/scifio/scifio-bf-compat/releases/tag/scifio-bf-compat-1.10.1
